export const VIETNAM_CITY_SUGGESTIONS = [
  "Ho Chi Minh City",
  "Hanoi",
  "Da Nang",
  "Can Tho",
  "Hai Phong",
  "Nha Trang",
  "Hue",
  "Vung Tau",
  "Da Lat",
  "Bien Hoa",
  "Quy Nhon",
  "Buon Ma Thuot",
  "Phu Quoc",
  "Ha Long",
  "Vinh",
  "Thanh Hoa",
  "Thai Nguyen",
  "Nam Dinh",
  "Rach Gia",
  "Phan Thiet",
] as const;

export const GLOBAL_CITY_SUGGESTIONS = [
  "Bangkok",
  "Singapore",
  "Kuala Lumpur",
  "Jakarta",
  "Manila",
  "Seoul",
  "Tokyo",
  "Osaka",
  "Taipei",
  "Hong Kong",
  "Shanghai",
  "Beijing",
  "Shenzhen",
  "Guangzhou",
  "Mumbai",
  "Delhi",
  "Bengaluru",
  "Dubai",
  "Istanbul",
  "Paris",
  "London",
  "Berlin",
  "Rome",
  "Madrid",
  "Amsterdam",
  "Zurich",
  "Stockholm",
  "Copenhagen",
  "New York",
  "Los Angeles",
  "San Francisco",
  "Chicago",
  "Toronto",
  "Vancouver",
  "Mexico City",
  "Sao Paulo",
  "Buenos Aires",
  "Sydney",
  "Melbourne",
  "Auckland",
  "Cape Town",
  "Cairo",
  "Nairobi",
  "Lisbon",
  "Prague",
] as const;

export const MAJOR_CITY_SUGGESTIONS = [
  ...VIETNAM_CITY_SUGGESTIONS,
  ...GLOBAL_CITY_SUGGESTIONS,
] as const;
